FROM golang:1.13.8s as builder

RUN apk update && \
    apk add make

COPY . /go/src/github.com/hendrikmaus/openhab-auth-router
WORKDIR /go/src/github.com/hendrikmaus/openhab-auth-router
RUN GOOS=linux GOARCH=arm GOARM=6 make build

FROM arm32v6/alpine

COPY --from=builder /go/src/github.com/hendrikmaus/openhab-auth-router/openhab-auth-router /usr/local/bin
