version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
    restart: always
    depends_on:
      - openhab-auth-router

  openhab-auth-router:
    image: gcr.io/distroless/base-debian10
    command: '/usr/local/bin/openhab-auth-router -host="0.0.0.0" -port="80" -target="http://openhab" -config="/usr/share/config.yaml" -log-level="debug"'
    ports:
      - 9090:80
    volumes:
      - ./config.yaml:/usr/share/config.yaml
      - ./:/usr/local/bin
    restart: always

  openhab:
    image: "openhab/openhab:2.5.1-amd64-debian"
    restart: always
    command: "./start_debug.sh"
    volumes:
      - ./openhab-conf/sitemaps:/openhab/conf/sitemaps
    tty: true
    environment:
      OPENHAB_HTTP_PORT: "80"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
    ports:
      - 8080:80
