name: End to End Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd testing
          ./test.sh
